name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy:
    # Only run on pushes or open/synced PRs
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Node.js (match the version you use locally)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # 3. Install dependencies (lockfile is in the repo root)
      - name: Install dependencies
        run: npm install

      # 4. Build your Next.js app
      - name: Build
        run: npm run build

      # 5. Deploy to Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_FIELD_04A40C30F }}
          repo_token:                             ${{ secrets.GITHUB_TOKEN }}
          action:                                upload
          app_location:                          "/"        # root of your Next.js project
          api_location:                          ""         # no Azure Functions in this repo
          output_location:                       ".next"    # Next.js build output folder

  close_pull_request:
    # run when a PR is closed, to clean up
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close PR
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_FIELD_04A40C30F }}
          action: close
